In [ ]:
Numpy

In [3]:
! pip install numpy

In [4]:
import numpy as np

In [5]:
array_one=np.array([1,2,3,4,5])
array_one

array([1, 2, 3, 4, 5])

In [6]:
type(array_one)

numpy.ndarray

In [7]:
num=[6,7,8,9,0]
array_two=np.array(num)
array_two

array([6, 7, 8, 9, 0])

In [8]:
type(array_two)

numpy.ndarray

In [ ]:
zero matrix

In [9]:
array_zeros=np.zeros((3,4))

In [10]:
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
Unit matrix using numpy

In [11]:
array_ones=np.ones((5,5))

In [12]:
array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#by befault all matrix elements are of float type

In [ ]:
#change the resultant matrix into int

In [15]:
array_zeros_int=np.zeros((3,4),dtype=np.int16)
array_zeros_int

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [16]:
array_ones_int=np.ones((5,5),dtype=np.int16)
array_ones_int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [ ]:
Identity matrix 

In [17]:
array_i=np.eye(5)
array_i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#print even no.s using numpy

In [18]:
array_even=np.arange(2,31,2)
array_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
#print odd numbers

In [19]:
array_odds=np.arange(1,31,2)
array_odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])